import 'package:flutter/material.dart';
import 'package:ionicons/ionicons.dart';

class AppIcons {
  static const IconData calendar = Ionicons.calendar_outline;
  static const IconData person = Ionicons.person;
  static const IconData forward = Ionicons.chevron_forward;
  static const IconData close = Ionicons.close;
  static const IconData sendMessage = Ionicons.send;
  static const IconData analytics = Ionicons.analytics;
  static const IconData chatBox = Ionicons.chatbox_ellipses;
  static const IconData arrowDown = Ionicons.arrow_down;
  static const IconData arrowUp = Ionicons.arrow_up;
  static const IconData settings = Ionicons.settings;
  static const IconData search = Ionicons.search;
  static const IconData camera = Ionicons.camera;
  static const IconData arrowBack = Ionicons.arrow_back;
  static const IconData barbell = Ionicons.barbell;
  static const IconData footSteps = Ionicons.footsteps;
  static const IconData battery = Ionicons.battery_charging;
  static const IconData rocket = Ionicons.rocket;
  static const IconData lock = Ionicons.lock_closed;
  static const IconData ribbon = Ionicons.ribbon;
  static const IconData flag = Ionicons.flag;
  static const IconData indicator = Ionicons.speedometer;
  static const IconData pulse = Ionicons.pulse;
  static const IconData food = Ionicons.fast_food;
  static const IconData fitness = Ionicons.fitness;
  static const IconData chevronBack = Ionicons.chevron_back;
  static const IconData bicycle = Ionicons.bicycle;
  static const IconData moon = Ionicons.moon_outline;
  static const IconData water = Ionicons.water_outline;
  static const IconData man = Ionicons.man;
  static const IconData woman = Ionicons.woman;
  static const IconData megaphone = Ionicons.megaphone_outline;
  static const IconData ai = Ionicons.hardware_chip_outline;
  static const IconData alert = Ionicons.alert;
  static const IconData language = Ionicons.earth;
  static const IconData documents = Ionicons.document_text;
  static const IconData cloud = Ionicons.cloud;
  static const IconData information = Ionicons.information_circle;
  static const IconData mail = Ionicons.mail;
  static const IconData image = Ionicons.image;
  static const IconData home = Ionicons.home;
  static const IconData time = Ionicons.time;
  static const IconData delete = Icons.delete;
  static const IconData done = Icons.done;
  static const IconData add = Icons.add;
  static const IconData draw = Icons.draw;
  static const IconData theme = Icons.format_color_fill_rounded;
  static const IconData chart = Icons.show_chart;
  static const IconData bed = Icons.hotel;
  static const IconData walk = Icons.directions_walk;
  static const IconData run = Icons.directions_run;
  static const IconData flash = Ionicons.flash;
}
